# Generated by Django 4.2.3 on 2023-08-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailer.mailinglist'),
        ),
    ]
